---
- name: Docker | Users | Gathering docker group information
  ansible.builtin.getent:
    database: group
    key: docker
    split: ':'

- name: Docker | Users | Check if all users are in docker group
  ansible.builtin.set_fact:
    at_least_one_user_not_in_docker_group: true
  with_items: "{{ docker_users }}"
  when: item not in ansible_facts.getent_group["docker"][2]

- name: Docker | Users | Make changes to the users
  when: at_least_one_user_not_in_docker_group is defined
  block:
    - name: Docker | Users | Ensure specified users are added to docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: true
      with_items: "{{ docker_users }}"

    - name: Docker | Users | Reset SHH connection to apply user changes
      ansible.builtin.meta: reset_connection
