---
blank_issues_link: false
contact_links:
  - name: Questions and Help
    url: https://github.com/Sombeyyy/ansible-role-docker/discussions
    about: This issue tracker is not for support questions. Please refer to our Discussions.
  - name: Feature Request
    url: https://github.com/Sombeyyy/ansible-role-docker/discussions/new?category=feature-requests
    about: Remember to search for existing feature requests and "up-vote" any you like
